<a href="https://colab.research.google.com/github/SnehaKotte/b20_1332/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Generate a 4x4 array of test scores (example: random integers 50–100)
scores = np.random.randint(50, 101, size=(4, 4))
print("Test Scores (4x4):\n", scores, "\n")

# Row-wise and column-wise means
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)

print("Row-wise Means:", row_means)
print("Column-wise Means:", col_means, "\n")

# Standard deviation and variance
std_dev = np.std(scores)
variance = np.var(scores)
print("Standard Deviation (overall):", std_dev)
print("Variance (overall):", variance, "\n")

# Global min and max with indices
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("Global Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index, "\n")

# Median
median = np.median(scores)
print("Median (overall):", median)

Test Scores (4x4):
 [[53 79 63 86]
 [50 55 95 53]
 [74 61 93 86]
 [80 61 89 96]] 

Row-wise Means: [70.25 63.25 78.5  81.5 ]
Column-wise Means: [64.25 64.   85.   80.25] 

Standard Deviation (overall): 16.069672523110107
Variance (overall): 258.234375 

Global Max: 96 at index (np.int64(3), np.int64(3))
Global Min: 50 at index (np.int64(1), np.int64(0)) 

Median (overall): 76.5


In [2]:
import numpy as np

# Create a 3x3x3 RGB image (values 0–255)
image = np.random.randint(0, 256, (3, 3, 3), dtype=np.uint8)
print("Original RGB Image Array:\n", image, "\n")

# Extract color channels using slicing
red_channel   = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel  = image[:, :, 2]

print("Red Channel:\n", red_channel, "\n")
print("Green Channel:\n", green_channel, "\n")
print("Blue Channel:\n", blue_channel, "\n")

# Average intensity per channel
avg_red   = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue  = np.mean(blue_channel)

print("Average Intensities - R:", avg_red,
      "G:", avg_green,
      "B:", avg_blue, "\n")

# Brighten image by adding scalar (clip to 255)
bright_image = np.clip(image + 50, 0, 255)
print("Brightened Image Array:\n", bright_image, "\n")

Original RGB Image Array:
 [[[210 114  34]
  [248  60 168]
  [123 165 143]]

 [[188  23 106]
  [ 44  42  71]
  [161 155 222]]

 [[ 13 232 135]
  [172  96 132]
  [176 201  20]]] 

Red Channel:
 [[210 248 123]
 [188  44 161]
 [ 13 172 176]] 

Green Channel:
 [[114  60 165]
 [ 23  42 155]
 [232  96 201]] 

Blue Channel:
 [[ 34 168 143]
 [106  71 222]
 [135 132  20]] 

Average Intensities - R: 148.33333333333334 G: 120.88888888888889 B: 114.55555555555556 

Brightened Image Array:
 [[[  4 164  84]
  [ 42 110 218]
  [173 215 193]]

 [[238  73 156]
  [ 94  92 121]
  [211 205  16]]

 [[ 63  26 185]
  [222 146 182]
  [226 251  70]]] 

